---
fullname: QuicksortComplexity
shortname: quicksort-complexity
organization: coq-contribs
community: false

synopsis: >-
  Proofs of Quicksort's worst- and average-case complexity in Coq

description: |
  The development contains:
  - a set of monads and monad transformers for measuring a (possibly nondeterministic) algorithm's use of designated operations;
  - monadically expressed deterministic and nondeterministic implementations of Quicksort;
  - proofs of these implementations' worst- and average case complexity.

paper:
  doi: 10.1007/978-3-642-02444-3_16
  url: http://www.cs.ru.nl/~james/2008-TYPES/final.pdf
  title: A Machine-Checked Proof of the Average-Case Complexity of Quicksort in Coq

authors:
- name: Eelis van der Weegen
  initial: true

opam-file-maintainer: palmskog@gmail.com

license:
  fullname: Public Domain
  identifier: Public Domain

supported_coq_versions:
  text: Coq 8.8 or later (use releases for other Coq versions)
  opam: '{(>= "8.8" & < "8.10~") | (= "dev")}'

tested_coq_versions:
- version_or_url: https://github.com/coq/coq-on-cachix/tarball/master
- version_or_url: 8.9
- version_or_url: 8.8

tested_coq_opam_version: dev

namespace: QuicksortComplexity

keywords:
- name: quicksort
- name: complexity
- name: average-case

categories:
- name: Computer Science/Decision Procedures and Certified Algorithms/Correctness proofs of algorithms
---
